# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LingGoApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # react-native-permissions: 声明需要使用的原生权限模块
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}"
  pod 'Permission-Microphone', :path => "#{permissions_path}"
  pod 'Permission-Notifications', :path => "#{permissions_path}"
  pod 'Permission-Contacts', :path => "#{permissions_path}"
  pod 'Permission-Calendars', :path => "#{permissions_path}"
  pod 'Permission-Reminders', :path => "#{permissions_path}"
  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}"
  pod 'Permission-Motion', :path => "#{permissions_path}"
  pod 'Permission-FaceID', :path => "#{permissions_path}"
  pod 'Permission-SpeechRecognition', :path => "#{permissions_path}"
  pod 'Permission-Siri', :path => "#{permissions_path}"
  pod 'Permission-Tracking', :path => "#{permissions_path}"

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
